version: "3.8"
services:
  autoapi-redis-staging:
    image: redis:latest
    container_name: autoapi-redis-staging
    restart: always
    ports:
      - "6381:6379"
  autoapi-redis-production:
    image: redis:latest
    container_name: autoapi-redis-production
    restart: always
    ports:
      - "6382:6379"
  autoapi-production:
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    container_name: autoapi-production
    restart: always
    depends_on:
      - autoapi-redis-production
    ports:
      - "8020:4000"
    volumes:
      - ./logs:/autoapi/logs
  autoapi-staging:
    build:
      context: ./
      dockerfile: ./Dockerfile.staging
    container_name: autoapi-staging
    restart: always
    depends_on:
      - autoapi-redis-staging
    ports:
      - "8030:4000"
    volumes:
      - ./logs:/autoapi/logs-staging
