#!/bin/bash
# Quick script to show your GitHub Secrets values
# Run this to get the values you need to paste into GitHub

echo "================================================"
echo "GITHUB SECRETS - Copy these values to GitHub"
echo "================================================"
echo ""

echo "1️⃣ SERVER CONNECTION SECRETS"
echo "================================"
echo ""
echo "DROPLET_IP:"
echo "146.190.115.74"
echo ""
echo "SSH_USER:"
echo "deploy"
echo ""
echo "SSH_PRIVATE_KEY:"
echo "⚠️  IMPORTANT: Copy EVERYTHING including -----BEGIN and -----END lines!"
echo ""
echo "Run this command and copy the COMPLETE output:"
echo "cat /Users/osmansamilerdogan/.ssh/autotable"
echo ""
echo "Your output should start with: -----BEGIN OPENSSH PRIVATE KEY-----"
echo "And end with: -----END OPENSSH PRIVATE KEY-----"
echo ""
echo "💡 TIP: Run this to copy directly to clipboard:"
echo "cat /Users/osmansamilerdogan/.ssh/autotable | pbcopy"
echo "Then paste into GitHub!"
echo ""

echo "2️⃣ APPLICATION CONFIGURATION"
echo "================================"
echo ""
echo "PORT_NUMBER:"
echo "4000"
echo ""

echo "3️⃣ GENERATE SECURITY SECRETS"
echo "================================"
echo "Run these commands and copy each output:"
echo ""
echo "JWT_SECRET:"
openssl rand -base64 32
echo ""
echo "CONTAINER_JWT_SECRET:"
openssl rand -base64 32
echo ""
echo "TENANT_JWT_SECRET:"
openssl rand -base64 32
echo ""

echo "4️⃣ MONGODB SECRETS"
echo "================================"
echo "Get these from your MongoDB Atlas dashboard"
echo ""
echo "MONGO_URI_BASE: mongodb+srv://username:password@cluster.mongodb.net/"
echo "COLLECTION_NAME: your_database_name"
echo "MONGO_URI_SUFFIX: ?retryWrites=true&w=majority"
echo ""

echo "5️⃣ CLOUDINARY SECRETS"
echo "================================"
echo "Get these from: https://cloudinary.com/console"
echo ""
echo "CLOUD_NAME: (from dashboard)"
echo "CLOUD_API_KEY: (from dashboard)"
echo "CLOUD_API_SECRET: (from dashboard)"
echo ""

echo "6️⃣ GOOGLE OAUTH SECRETS"
echo "================================"
echo "Get these from: https://console.cloud.google.com/"
echo "Go to: APIs & Services → Credentials"
echo ""
echo "GOOGLE_CLIENT_ID: (from Google Cloud Console)"
echo "GOOGLE_CLIENT_SECRET: (from Google Cloud Console)"
echo "GOOGLE_REDIRECT_URL: http://146.190.115.74:4000/auth/google/callback"
echo ""

echo "7️⃣ URL CONFIGURATION"
echo "================================"
echo ""
echo "BACKEND_BASE_URL: http://146.190.115.74:4000"
echo "FRONTEND_URL: (your frontend URL)"
echo ""

echo "================================================"
echo "✅ NEXT STEPS:"
echo "================================================"
echo "1. Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo "2. Click 'New repository secret' for each value above"
echo "3. Copy and paste each value exactly"
echo "4. Push to main: git push origin main"
echo ""
