name: Go CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.3"

      - name: Install Dependencies
        run: go mod download

      - name: Build Application
        run: go build -o app .

      - name: Run Tests
        run: go test -v ./...

      - name: Create .env file
        run: |
          echo CLOUD_NAME=${{ secrets.CLOUD_NAME }} >> .env
          echo CLOUD_API_KEY=${{ secrets.CLOUD_API_KEY }} >> .env
          echo CLOUD_API_SECRET=${{ secrets.CLOUD_API_SECRET }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET}} >> .env
          echo CONTAINER_JWT_SECRET=${{secrets.CONTAINER_JWT_SECRET}} >> .env
          echo PORT_NUMBER=${{secrets.PORT_NUMBER}} >> .env
          echo MONGO_URI_BASE=${{secrets.MONGO_URI_BASE}} >> .env
          echo MONGO_URI_SUFFIX=${{secrets.MONGO_URI_SUFFIX}} >> .env
      - name: Create ssh folder
        run: |
          mkdir -p ~/.ssh
      - name: Adding private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
      - name: Changing permissons of private key
        run: |
          chmod 700 ~/.ssh/id_rsa
      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Rsync files to remote host
        run: |
          rsync -avz -r -e "ssh -i .ssh/id_rsa" ./config .env Dockerfile.production Dockerfile.staging docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:app
      - name: Run deploy command on remote host
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd app && sudo docker-compose up -d --build autoapi-staging && sudo docker system prune -af"
